SPECIES_METADATA = {
    0: {
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": [], "great_one": False},
        "European Bison": {"max_level": 5, "diamond_min": 127.62, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "European Rabbit": {"max_level": 3, "diamond_min": 2.42, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Leucistic\n Light Brown\n Light Grey\n Melanistic\n Tan"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino\n Chocolate\n Dark\n Dark Spotted\n Melanistic\n Piebald\n Red Spotted\n Spotted\n White \n Golden\n Mocha\n Hooded\n Silver"], "great_one": True},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Roe Deer": {"max_level": 3, "diamond_min": 81.86, "rare_furs": ["Albino\n Brown\n Dark Brown\n Dark Grey\n Leucistic\n Melanistic\n Orange\n Piebald\n Tan"], "great_one": True},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Brown\n Dark Brown\n Light Brown\n Melanistic\n Purplegrey\n\n Brindle\n Butterscotch\n Chalk\n Cinder\n Scorch\n Smolder\n Stitch\n Stripple"], "great_one": True},
    },
    1: {
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Black\n Blonde\n Brown\n Cinnamon\n Dark\n Dusky\n\n Cream\n Spotted\n Spirit\n Chestnut"], "great_one": True},
        "Blacktail Deer": {"max_level": 5, "diamond_min": 177.50, "rare_furs": ["Albino\n Dark Grey\n Grey\n Grey-Brown\n Melanistic\n Piebald\n Tan"], "great_one": False},
        "Coyote": {"max_level": 9, "diamond_min": 56.80, "rare_furs": ["Albino\n Dark-Grey\n Grey-Brown\n Light Grey\n Melanistic\n Orange\n Piebald"], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Merriam Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": [], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Roosevelt Elk": {"max_level": 5, "diamond_min": 380.80, "rare_furs": ["Albino\n Brown\n Melanistic\n Orange\n Piebald\n Tan"], "great_one": False},
        "White-tailed Jackrabbit": {"max_level": 3, "diamond_min": 6.30, "rare_furs": ["Albino\n Beige\n Brown\n Grey\n Light Brown"], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
    },
    2: {
        "Eurasian Brown Bear": {"max_level": 9, "diamond_min": 27.70, "rare_furs": ["Albino\n Blond\n Cinnamon\n Dark Brown\n Gold\n Grey\n Light Brown\n Melanistic\n Red-Brown\n Spirit"], "great_one": False},
        "Eurasian Lynx": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino\n Grey\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "Gray Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Egg White\n Dark Grey\n Grey\n Melanistic\n Melanistic Charcoal\n Red Brown\n\n Dawnbreak\n Frostbite\n Gravehide\n Hollow\n Razorwind\n Scarborne\n Twinsoul\n Vanguard"], "great_one": True},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Mountain Reindeer": {"max_level": 5, "diamond_min": 430.23, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald\n Tan"], "great_one": False},
        "Siberian Musk Deer": {"max_level": 3, "diamond_min": 249.00, "rare_furs": ["Albino\n Dark Brown\n Grey Brown\n Melanistic\n Orange\n Piebald"], "great_one": False},
        "Western Capercaillie": {"max_level": 3, "diamond_min": 4.64, "rare_furs": [], "great_one": False},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Brown\n Dark Brown\n Light Brown\n Melanistic\n Purplegrey\n\n Brindle\n Butterscotch\n Chalk\n Cinder\n Scorch\n Smolder\n Stitch\n Stripple"], "great_one": True},
    },
    3: {
        "Blue Wildebeest": {"max_level": 5, "diamond_min": 37.60, "rare_furs": ["Albino\n Crowned\n Dark Grey\n Gold\n Grey"], "great_one": False},
        "Cape Buffalo": {"max_level": 9, "diamond_min": 151.35, "rare_furs": ["Albino\n Black\n Brown\n Grey\n Leucistic"], "great_one": False},
        "Eurasian Wigeon": {"max_level": 3, "diamond_min": 905.00, "rare_furs": [], "great_one": False},
        "Gemsbok": {"max_level": 5, "diamond_min": 337.50, "rare_furs": ["Beige\n Dark\n Grey\n Light Grey\n Gold"], "great_one": False},
        "Lesser Kudu": {"max_level": 5, "diamond_min": 151.60, "rare_furs": ["Albino\n Grey\n Dark Brown\n Dusky\n Melanistic\n Red Brown"], "great_one": False},
        "Lion": {"max_level": 9, "diamond_min": 48.50, "rare_furs": ["Albino\n Blonde\n Dark-Brown\n Light Brown\n Tan"], "great_one": False},
        "Scrub Hare": {"max_level": 3, "diamond_min": 5.30, "rare_furs": ["Brown\n Chestnut\n Grey\n Light Gray"], "great_one": False},
        "Side-Striped Jackal": {"max_level": 9, "diamond_min": 29.10, "rare_furs": ["Albino\n Light Brown\n Grey\n Grey Brown\n Melanistic"], "great_one": False},
        "Springbok": {"max_level": 5, "diamond_min": 78.55, "rare_furs": ["'Albino\n Black Brown\n Orange\n Tan"], "great_one": False},
        "Warthog": {"max_level": 5, "diamond_min": 58.20, "rare_furs": ["Albino\n Dark\n Grey\n Red Brown\n Red"], "great_one": False},
    },
    4: {
        "Axis Deer": {"max_level": 5, "diamond_min": 217.20, "rare_furs": ["Albino\n Dark\n Melanistic\n Orange\n Piebald\n Spotted"], "great_one": False},
        "Blackbuck": {"max_level": 5, "diamond_min": 132.20, "rare_furs": ["Albino\n Beige\n Brown\n Dark Brown\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Cinnamon Teal": {"max_level": 3, "diamond_min": 4.60, "rare_furs": [], "great_one": False},
        "Collared Peccary": {"max_level": 5, "diamond_min": 144.20, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Dark-Grey\n Grey\n Leucistic\n Melanistic\n Ochre"], "great_one": False},
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino\n Blonde\n Brown\n Dilute\n Erythristic Isabelline\n Erythristic Red\n Grey\n Leucistic\n Melanistic\n Mosaic\n Piebald\n\n Cobweb Enigma\n Dripple Drizzle\n Dusky Drift\n Milky Way\n Petal Puff"], "great_one": True},
        "Puma": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino\n Dark Red\n Grey\n Light Brown\n Melanistic"], "great_one": False},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Water Buffalo": {"max_level": 9, "diamond_min": 167.54, "rare_furs": ["Albino\n Black\n Brown\n Grey\n Orange"], "great_one": False},
    },
    6: {
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": [], "great_one": False},
        "Grant Caribou": {"max_level": 5, "diamond_min": 430.23, "rare_furs": ["Albino\n Dark Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "Gray Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Egg White\n Dark Grey\n Grey\n Melanistic\n Melanistic Charcoal\n Red Brown\n\n Dawnbreak\n Frostbite\n Gravehide\n Hollow\n Razorwind\n Scarborne\n Twinsoul\n Vanguard"], "great_one": True},
        "Grizzly Bear": {"max_level": 9, "diamond_min": 66.94, "rare_furs": ["Albino\n Brown\n Grey Brown\n Melanistic"], "great_one": False},
        "Harlequin Duck": {"max_level": 3, "diamond_min": 7.23, "rare_furs": [], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Plains Bison": {"max_level": 5, "diamond_min": 183.50, "rare_furs": ["Albino\n Brown\n Dark\n Light Brown\n Light Grey\n Leucistic\n Melanistic"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
    },
    8: {
        "Beceite Ibex": {"max_level": 5, "diamond_min": 191.63, "rare_furs": ["Albino\n Brown Hybrid\n Buff\n Grey\n Grey-Brown\n Light Brown\n Melanistic\n Orange"], "great_one": False},
        "European Hare": {"max_level": 3, "diamond_min": 6.50, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Light Brown\n Grey\n Melanistic"], "great_one": False},
        "Gredos Ibex": {"max_level": 5, "diamond_min": 100.17, "rare_furs": ["Albino\n Brown Hybrid\n Buff\n Gray Brown\n Grey\n Light Brown\n Light Grey\n Melanistic"], "great_one": False},
        "Iberian Mouflon": {"max_level": 5, "diamond_min": 179.56, "rare_furs": ["Albino\n Brown\n Grey\n Light Brown\n Melanistic"], "great_one": False},
        "Iberian Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino\n Grey\n Grey-Brown\n Melanistic\n Olive\n Pristine\n Winter\nMission Exclusive: Ogro\n Sombra\n Fantasma"], "great_one": False},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Roe Deer": {"max_level": 3, "diamond_min": 81.86, "rare_furs": ["Albino\n Brown\n Dark Brown\n Dark Grey\n Leucistic\n Melanistic\n Orange\n Piebald\n Tan"], "great_one": True},
        "Ronda Ibex": {"max_level": 5, "diamond_min": 107.98, "rare_furs": ["Albino\n Brown\n Brown Hybrid\n Buff\n Grey\n Grey-Brown\n Melanistic"], "great_one": False},
        "Southeastern Spanish Ibex": {"max_level": 5, "diamond_min": 89.68, "rare_furs": ["Albino\n Brown Hybrid\n Buff\n Grey-Brown\n Light Brown\n Light Grey\n Melanistic\n Orange"], "great_one": False},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Brown\n Dark Brown\n Light Brown\n Melanistic\n Purplegrey\n\n Brindle\n Butterscotch\n Chalk\n Cinder\n Scorch\n Smolder\n Stitch\n Stripple"], "great_one": True},
    },
    9: {
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Black\n Blonde\n Brown\n Cinnamon\n Dark\n Dusky\n\n Cream\n Spotted\n Spirit\n Chestnut"], "great_one": True},
        "Merriam Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": [], "great_one": False},
        "Mountain Goat": {"max_level": 5, "diamond_min": 107.67, "rare_furs": ["Albino\n Beige\n Light Brown\n Light Grey\n Melanistic\n White"], "great_one": False},
        "Mountain Lion": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino\n Dark Red\n Grey\n Light Brown\n Melanistic"], "great_one": False},
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino\n Blonde\n Brown\n Dilute\n Erythristic Isabelline\n Erythristic Red\n Grey\n Leucistic\n Melanistic\n Mosaic\n Piebald\n\n Cobweb Enigma\n Dripple Drizzle\n Dusky Drift\n Milky Way\n Petal Puff"], "great_one": True},
        "Plains Bison": {"max_level": 5, "diamond_min": 183.50, "rare_furs": ["Albino\n Brown\n Dark\n Light Brown\n Light Grey\n Leucistic\n Melanistic"], "great_one": False},
        "Pronghorn": {"max_level": 5, "diamond_min": 108.00, "rare_furs": ["Albino\n Brown\n Dark\n Leucistic\n Melanistic\n Piebald\n Tan"], "great_one": False},
        "Rocky Mountain Bighorn Sheep": {"max_level": 5, "diamond_min": 196.93, "rare_furs": ["Albino\n Black\n Bronze\n Brown\n Grey\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Rocky Mountain Elk": {"max_level": 5, "diamond_min": 481.41, "rare_furs": ["Albino\n Brown\n Common\n Light Grey\n Piebald"], "great_one": False},
    },
    10: {
        "Chamois": {"max_level": 5, "diamond_min": 58.00, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Grey Brown\n Honeytones\n Leucistic\n Melanistic"], "great_one": False},
        "European Rabbit": {"max_level": 3, "diamond_min": 2.42, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Leucistic\n Light Brown\n Light Grey\n Melanistic\n Tan"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino\n Chocolate\n Dark\n Dark Spotted\n Melanistic\n Piebald\n Red Spotted\n Spotted\n White \n Golden\n Mocha\n Hooded\n Silver"], "great_one": True},
        "Feral Goat": {"max_level": 5, "diamond_min": 208.71, "rare_furs": ["Albino\n Black\n Black Brown\n Back White\n Blonde\n Brown\n Dark Brown\n Mixed\n White\n White Brown"], "great_one": False},
        "Feral Pig": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Black Spots\n Black\n Brown Hybrid\n Dark Brown\n Pink"], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Merriam Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": [], "great_one": False},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Sika Deer": {"max_level": 5, "diamond_min": 198.74, "rare_furs": ["Albino\n Black\n Brown\n Dark Spotted\n Red Spotted\n Spotted"], "great_one": False},
        "Tahr": {"max_level": 5, "diamond_min": 101.87, "rare_furs": ["Albino\n Black\n Dark Brown\n Dark Red\n Light Brown\n Red\n Red Brown\n Straw\n White\n\n Gray\n Half\n Latte\n Scars\n Skull\n Snow"], "great_one": True},
    },
    11: {
        "Antelope Jackrabbit": {"max_level": 3, "diamond_min": 6.30, "rare_furs": ["Albino\n Brown\n Dark Brown\n Grey\n Melanistic\n Mottled"], "great_one": False},
        "Collared Peccary": {"max_level": 5, "diamond_min": 144.20, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Dark-Grey\n Grey\n Leucistic\n Melanistic\n Ochre"], "great_one": False},
        "Coyote": {"max_level": 9, "diamond_min": 56.80, "rare_furs": ["Albino\n Dark-Grey\n Grey-Brown\n Light Grey\n Melanistic\n Orange\n Piebald"], "great_one": False},
        "Desert Bighorn Sheep": {"max_level": 5, "diamond_min": 196.93, "rare_furs": ["Albino\n Brown\n Erythristic\n Grey\n Leucistic\n Light Brown\n Light Grey\n Piebald\n Melanistic\n Mosaic"], "great_one": False},
        "Mexican Bobcat": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino\n Blue\n Brown\n Grey\n Melanistic\n Tan\n Red"], "great_one": False},
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino\n Blonde\n Brown\n Dilute\n Erythristic Isabelline\n Erythristic Red\n Grey\n Leucistic\n Melanistic\n Mosaic\n Piebald\n\n Cobweb Enigma\n Dripple Drizzle\n Dusky Drift\n Milky Way\n Petal Puff"], "great_one": True},
        "Pronghorn": {"max_level": 5, "diamond_min": 108.00, "rare_furs": ["Albino\n Brown\n Dark\n Leucistic\n Melanistic\n Piebald\n Tan"], "great_one": False},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Rio Grande Turkey": {"max_level": 3, "diamond_min": 4.60, "rare_furs": [], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
    },
    12: {
        "American Alligator": {"max_level": 9, "diamond_min": 492.00, "rare_furs": ["Albino\n Dark-Brown\n Melanistic\n Olive\n Piebald"], "great_one": False},
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Black\n Blonde\n Brown\n Cinnamon\n Dark\n Dusky\n\n Cream\n Spotted\n Spirit\n Chestnut"], "great_one": True},
        "Bobwhite Quail": {"max_level": 3, "diamond_min": 238.00, "rare_furs": [], "great_one": False},
        "Common Raccoon": {"max_level": 5, "diamond_min": 12.00, "rare_furs": ["Albino\n Blonde\n Blonde Piebald\n Brown\n Grey\n Grey Piebald\n Melanistic"], "great_one": False},
        "Eastern Cottontail Rabbit": {"max_level": 3, "diamond_min": 1.97, "rare_furs": ["Albino\n Brown\n Grey\n Leucistic\n Light Grey\n Melanistic"], "great_one": False},
        "Eastern Wild Turkey": {"max_level": 3, "diamond_min": 4.60, "rare_furs": [], "great_one": False},
        "Gray Fox": {"max_level": 9, "diamond_min": 6.43, "rare_furs": ["Albino\n Grey\n Leucistic\n Melanistic\n Piebald\n Red\n Two Tones"], "great_one": False},
        "Green Winged Teal": {"max_level": 3, "diamond_min": 480.00, "rare_furs": [], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
        "Wild Hog": {"max_level": 5, "diamond_min": 144.20, "rare_furs": ["Albino\n Black\n Black Spots\n Blackgold\n Brown Hybrid\n Dark Brown\n Pink"], "great_one": False},
    },
    13: {
        "Black Grouse": {"max_level": 3, "diamond_min": 120.00, "rare_furs": [], "great_one": False},
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": [], "great_one": False},
        "Eurasian Brown Bear": {"max_level": 9, "diamond_min": 27.70, "rare_furs": ["Albino\n Blond\n Cinnamon\n Dark Brown\n Gold\n Grey\n Light Brown\n Melanistic\n Red-Brown\n Spirit"], "great_one": False},
        "Eurasian Lynx": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino\n Grey\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "Eurasian Teal": {"max_level": 3, "diamond_min": 354.00, "rare_furs": [], "great_one": False},
        "Eurasian Wigeon": {"max_level": 3, "diamond_min": 905.00, "rare_furs": [], "great_one": False},
        "Goldeneye": {"max_level": 3, "diamond_min": 1230.00, "rare_furs": [], "great_one": False},
        "Greylag Goose": {"max_level": 5, "diamond_min": 3.85, "rare_furs": [], "great_one": False},
        "Hazel Grouse": {"max_level": 3, "diamond_min": 435.00, "rare_furs": [], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Mountain Hare": {"max_level": 3, "diamond_min": 5.60, "rare_furs": ["Albino\n Dark Brown\n Dark Grey\n Grey\n Light Brown\n Molting\n White"], "great_one": False},
        "Raccoon Dog": {"max_level": 9, "diamond_min": 9.29, "rare_furs": ["Albino\n Black White\n Dark Brown\n Light Brown\n Grey\n Orange\n Piebald"], "great_one": False},
        "Rock Ptarmigan": {"max_level": 3, "diamond_min": 709.00, "rare_furs": [], "great_one": False},
        "Tufted Duck": {"max_level": 3, "diamond_min": 963.00, "rare_furs": [], "great_one": False},
        "Tundra Bean Goose": {"max_level": 5, "diamond_min": 3.16, "rare_furs": [], "great_one": False},
        "Western Capercaillie": {"max_level": 3, "diamond_min": 4.64, "rare_furs": [], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
        "Willow Ptarmigan": {"max_level": 3, "diamond_min": 772.00, "rare_furs": [], "great_one": False},
    },
    14: {
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Black\n Blonde\n Brown\n Cinnamon\n Dark\n Dusky\n\n Cream\n Spotted\n Spirit\n Chestnut"], "great_one": True},
        "Bobcat": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino\n Blue\n Brown\n Grey\n Melanistic\n Red\n Tan"], "great_one": False},
        "Bobwhite Quail": {"max_level": 3, "diamond_min": 238.00, "rare_furs": [], "great_one": False},
        "Common Raccoon": {"max_level": 5, "diamond_min": 12.00, "rare_furs": ["Albino\n Blonde\n Blonde Piebald\n Brown\n Grey\n Grey Piebald\n Melanistic"], "great_one": False},
        "Coyote": {"max_level": 9, "diamond_min": 56.80, "rare_furs": ["Albino\n Dark-Grey\n Grey-Brown\n Light Grey\n Melanistic\n Orange\n Piebald"], "great_one": False},
        "Eastern Cottontail Rabbit": {"max_level": 3, "diamond_min": 1.97, "rare_furs": ["Albino\n Brown\n Grey\n Leucistic\n Light Grey\n Melanistic"], "great_one": False},
        "Eastern Wild Turkey": {"max_level": 3, "diamond_min": 4.60, "rare_furs": [], "great_one": False},
        "Goldeneye": {"max_level": 3, "diamond_min": 1230.00, "rare_furs": [], "great_one": False},
        "Gray Fox": {"max_level": 9, "diamond_min": 6.43, "rare_furs": ["Albino\n Grey\n Leucistic\n Melanistic\n Piebald\n Red\n Two Tones"], "great_one": False},
        "Green Winged Teal": {"max_level": 3, "diamond_min": 480.00, "rare_furs": [], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
    },
    16: {
        "Axis Deer": {"max_level": 5, "diamond_min": 217.20, "rare_furs": ["Albino\n Dark\n Melanistic\n Orange\n Piebald\n Spotted"], "great_one": False},
        "Banteng": {"max_level": 5, "diamond_min": 137.00, "rare_furs": ["Albino\n Black\n Brown\n Dark Brown\n Mocha\n Orange\n Melanistic"], "great_one": False},
        "Eastern Gray Kangaroo": {"max_level": 9, "diamond_min": 492.00, "rare_furs": ["Albino\n Grey Brown\n Grey\n Leucistic\n Melanistic\n Brown"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino\n Chocolate\n Dark\n Dark Spotted\n Melanistic\n Piebald\n Red Spotted\n Spotted\n White \n Golden\n Mocha\n Hooded\n Silver"], "great_one": True},
        "Feral Goat": {"max_level": 5, "diamond_min": 208.71, "rare_furs": ["Albino\n Black\n Black Brown\n Back White\n Blonde\n Brown\n Dark Brown\n Mixed\n White\n White Brown"], "great_one": False},
        "Feral Pig": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Black Spots\n Black\n Brown Hybrid\n Dark Brown\n Pink"], "great_one": False},
        "Hog Deer": {"max_level": 5, "diamond_min": 108.68, "rare_furs": ["Spotted\n Dark Spotted\n Dark Brown\n Piebald\n Leucistic\n Brown"], "great_one": False},
        "Javan Rusa": {"max_level": 5, "diamond_min": 148.78, "rare_furs": ["Albino\n Brown\n Leucistic\n Light Brown\n Piebald\n Two Tones\n White Brown"], "great_one": False},
        "Magpie Goose": {"max_level": 5, "diamond_min": 3.02, "rare_furs": [], "great_one": False},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
        "Saltwater Crocodile": {"max_level": 9, "diamond_min": 1015.00, "rare_furs": ["Albino\n Grey\n Dark Brown\n Leucistic\n Light Brown\n Melanistic\n Olive\n Piebald"], "great_one": False},
        "Sambar": {"max_level": 5, "diamond_min": 166.24, "rare_furs": ["Albino\n Brown\n Dark Brown\n Dusky Gradient\n Leucistic\n Light Brown\n Piebald"], "great_one": False},
        "Stubble Quail": {"max_level": 3, "diamond_min": 126.00, "rare_furs": [], "great_one": False},
    },
    17: {
        "Barasingha": {"max_level": 5, "diamond_min": 226.05, "rare_furs": ["Albino\n Brown\n Dark Brown\n Dark Red\n Leucistic\n Light Brown\n Melanistic\n Piebald\n Red"], "great_one": False},
        "Bengal Tiger": {"max_level": 9, "diamond_min": 57.00, "rare_furs": ["Albino\n Gold\n Orange\n Pseudo-Melanistic\n Pseudo-Melanistic White\n Melanistic\n White\n White Stripeless"], "great_one": False},
        "Blackbuck": {"max_level": 5, "diamond_min": 132.20, "rare_furs": ["Albino\n Beige\n Brown\n Dark Brown\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Blue Sheep": {"max_level": 5, "diamond_min": 154.08, "rare_furs": ["Albino\n Blue Gray\n Brown\n Leucistic\n Melanistic\n Slate Gray\n Yellow"], "great_one": False},
        "Greylag Goose": {"max_level": 5, "diamond_min": 3.85, "rare_furs": [], "great_one": False},
        "Nilgai": {"max_level": 5, "diamond_min": 94.89, "rare_furs": ["Blue\n Brown\n Dark Brown\n Light Brown\n Piebald"], "great_one": False},
        "Northern Red Muntjac": {"max_level": 5, "diamond_min": 35.24, "rare_furs": ["Albino \n Leucistic\n Melanistic\n Red"], "great_one": False},
        "Snow Leopard": {"max_level": 9, "diamond_min": 29.00, "rare_furs": ["Albino\n Caramel\n Leucistic\n Melanistic\n Snow"], "great_one": False},
        "Tahr": {"max_level": 5, "diamond_min": 101.87, "rare_furs": ["Albino\n Black\n Dark Brown\n Dark Red\n Light Brown\n Red\n Red Brown\n Straw\n White\n\n Gray\n Half\n Latte\n Scars\n Skull\n Snow"], "great_one": True},
        "Tibetan Fox": {"max_level": 9, "diamond_min": 6.37, "rare_furs": ["Albino\n Grey\n Leucistic\n Melanistic\n Orange\n Red\n Sand\n Smoke\n Tawny"], "great_one": False},
        "Water Buffalo": {"max_level": 9, "diamond_min": 167.54, "rare_furs": ["Albino\n Black\n Brown\n Grey\n Orange"], "great_one": False},
        "Wild Yak": {"max_level": 9, "diamond_min": 273.23, "rare_furs": ["Albino\n Dark Brown\n Dark Red\n Dark Red Brown\n Gold\n Jet Black\n Jet Brown\n Leucistic"], "great_one": False},
        "Woolly Hare": {"max_level": 3, "diamond_min": 3.28, "rare_furs": ["Albino\n Dark Brown\n Light Brown\n Light Grey\n Molting\n White"], "great_one": False},
    },
    18: {
        "Black Grouse": {"max_level": 3, "diamond_min": 120.00, "rare_furs": [], "great_one": False},
        "Common Raccoon": {"max_level": 5, "diamond_min": 12.00, "rare_furs": ["Albino\n Blonde\n Blonde Piebald\n Brown\n Grey\n Grey Piebald\n Melanistic"], "great_one": False},
        "Eurasian Teal": {"max_level": 3, "diamond_min": 354.00, "rare_furs": [], "great_one": False},
        "Eurasian Wigeon": {"max_level": 3, "diamond_min": 905.00, "rare_furs": [], "great_one": False},
        "European Rabbit": {"max_level": 3, "diamond_min": 2.42, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Leucistic\n Light Brown\n Light Grey\n Melanistic\n Tan"], "great_one": False},
        "Ferruginous Duck": {"max_level": 3, "diamond_min": 1050.00, "rare_furs": [], "great_one": False},
        "Gadwall": {"max_level": 3, "diamond_min": 1050.00, "rare_furs": [], "great_one": False},
        "Goldeneye": {"max_level": 3, "diamond_min": 1230.00, "rare_furs": [], "great_one": False},
        "Greylag Goose": {"max_level": 5, "diamond_min": 3.85, "rare_furs": [], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Raccoon Dog": {"max_level": 9, "diamond_min": 9.29, "rare_furs": ["Albino\n Black White\n Dark Brown\n Light Brown\n Grey\n Orange\n Piebald"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Tufted Duck": {"max_level": 3, "diamond_min": 963.00, "rare_furs": [], "great_one": False},
        "Tundra Bean Goose": {"max_level": 5, "diamond_min": 3.16, "rare_furs": [], "great_one": False},
    },
    19: {
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Black\n Blonde\n Brown\n Cinnamon\n Dark\n Dusky\n\n Cream\n Spotted\n Spirit\n Chestnut"], "great_one": True},
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": [], "great_one": False},
        "Dusky Grouse": {"max_level": 3, "diamond_min": 151.00, "rare_furs": [], "great_one": False},
        "Gray Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Egg White\n Dark Grey\n Grey\n Melanistic\n Melanistic Charcoal\n Red Brown\n\n Dawnbreak\n Frostbite\n Gravehide\n Hollow\n Razorwind\n Scarborne\n Twinsoul\n Vanguard"], "great_one": True},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": [], "great_one": False},
        "Manitoban Elk": {"max_level": 5, "diamond_min": 457.56, "rare_furs": ["Albino\n Brown Maned\n Dark\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Acromelanistic\n Albino\n Brown\n Dark-Brown\n Light Brown\n Melanistic\n Mosaic\n Piebald\n Tan\nMission Exclusive: Mocha \n Two Tone\n Ashen\n Birch\n Oak\n Speckled"], "great_one": True},
        "Mountain Goat": {"max_level": 5, "diamond_min": 107.67, "rare_furs": ["Albino\n Beige\n Light Brown\n Light Grey\n Melanistic\n White"], "great_one": False},
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino\n Blonde\n Brown\n Dilute\n Erythristic Isabelline\n Erythristic Red\n Grey\n Leucistic\n Melanistic\n Mosaic\n Piebald\n\n Cobweb Enigma\n Dripple Drizzle\n Dusky Drift\n Milky Way\n Petal Puff"], "great_one": True},
        "North American Beaver": {"max_level": 5, "diamond_min": 30.40, "rare_furs": ["Albino\n Dark Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald\n Reddish Brown"], "great_one": False},
        "Northern Pintail": {"max_level": 3, "diamond_min": 1040.00, "rare_furs": [], "great_one": False},
        "Pronghorn": {"max_level": 5, "diamond_min": 108.00, "rare_furs": ["Albino\n Brown\n Dark\n Leucistic\n Melanistic\n Piebald\n Tan"], "great_one": False},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Rocky Mountain Bighorn Sheep": {"max_level": 5, "diamond_min": 196.93, "rare_furs": ["Albino\n Black\n Bronze\n Brown\n Grey\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Snow Goose": {"max_level": 5, "diamond_min": 3.85, "rare_furs": [], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
        "Wood Bison": {"max_level": 5, "diamond_min": 158.00, "rare_furs": ["Albino\n Dark Brown\n Ginger\n Ginger Split\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "Wood Duck": {"max_level": 3, "diamond_min": 670.00, "rare_furs": [], "great_one": False},
        "Woodland Caribou": {"max_level": 5, "diamond_min": 430.23, "rare_furs": ["Albino\n Dark Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
    },
    20: {
        "American Mink": {"max_level": 5, "diamond_min": 151.00, "rare_furs": ["Albino\n Black\n Chestnut\n Dark Brown\n Leucistic\n Melanistic\n Piebald\n Silver"], "great_one": False},
        "Black Grouse": {"max_level": 3, "diamond_min": 120.00, "rare_furs": [], "great_one": False},
        "Eurasian Pine Marten": {"max_level": 5, "diamond_min": 208.00, "rare_furs": ["Albino\n Black\n Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald\n Tawny"], "great_one": False},
        "Eurasian Wigeon": {"max_level": 3, "diamond_min": 905.00, "rare_furs": [], "great_one": False},
        "Eurasian Woodcock": {"max_level": 3, "diamond_min": 41.03, "rare_furs": [], "great_one": False},
        "European Badger": {"max_level": 5, "diamond_min": 16.00, "rare_furs": ["Albino\n Brown\n Dark Grey\n Dilute\n Erythristic Red\n Grey\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino\n Chocolate\n Dark\n Dark Spotted\n Melanistic\n Piebald\n Red Spotted\n Spotted\n White \n Golden\n Mocha\n Hooded\n Silver"], "great_one": True},
        "Feral Goat": {"max_level": 5, "diamond_min": 208.71, "rare_furs": ["Albino\n Black\n Black Brown\n Back White\n Blonde\n Brown\n Dark Brown\n Mixed\n White\n White Brown"], "great_one": False},
        "Mountain Hare": {"max_level": 3, "diamond_min": 5.60, "rare_furs": ["Albino\n Dark Brown\n Dark Grey\n Grey\n Light Brown\n Molting\n White"], "great_one": False},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino\n Brown\n Dark Brown\n Erythristic\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino\n Dark Red\n Melanistic\n Orange\n Piebald\n Red\n\n Candycane\n Cherry Blossom\n Licorice\n Midnight Poppy\n Mystic Snowdrop\n Peppermint\n Rosebud Frost\n Scarlet Nightshade"], "great_one": True},
        "Red Grouse": {"max_level": 3, "diamond_min": 72.75, "rare_furs": [], "great_one": False},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 20.30, "rare_furs": [], "great_one": True},
        "Roe Deer": {"max_level": 3, "diamond_min": 81.86, "rare_furs": ["Albino\n Brown\n Dark Brown\n Dark Grey\n Leucistic\n Melanistic\n Orange\n Piebald\n Tan"], "great_one": True},
        "Sika Deer": {"max_level": 5, "diamond_min": 198.74, "rare_furs": ["Albino\n Black\n Brown\n Dark Spotted\n Red Spotted\n Spotted"], "great_one": False},
        "Western Capercaillie": {"max_level": 3, "diamond_min": 4.64, "rare_furs": [], "great_one": False},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino\n Blackgold\n Brown\n Dark Brown\n Light Brown\n Melanistic\n Purplegrey\n\n Brindle\n Butterscotch\n Chalk\n Cinder\n Scorch\n Smolder\n Stitch\n Stripple"], "great_one": True},
    },
    21: {
        "Black Caiman": {"max_level": 9, "diamond_min": 468.00, "rare_furs": ["Albino\n Dark Green\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Capybara": {"max_level": 4, "diamond_min": 66.50, "rare_furs": ["Albino\n Dark Brown\n Leucistic\n Light Brown\n Melanistic\n Piebald"], "great_one": False},
        "Cinnamon Teal": {"max_level": 3, "diamond_min": 4.60, "rare_furs": [], "great_one": False},
        "Collared Peccary": {"max_level": 5, "diamond_min": 144.20, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Dark-Grey\n Grey\n Leucistic\n Melanistic\n Ochre"], "great_one": False},
        "Greater Grison": {"max_level": 5, "diamond_min": 356.00, "rare_furs": ["Albino\n Dark\n Erythristic Chocolate\n Grey\n Leucistic\n Melanistic\n Pale\n Piebald"], "great_one": False},
        "Jaguar": {"max_level": 9, "diamond_min": 43.75, "rare_furs": ["Spotted\n Rosetted\n Melanistic Charcoal\n Melanistic\n Pseudo-Melanistic\n Piebald\n Leucistic\n Albino \n Ivorybark\n Porcelain\n Rosewash\n Tapestry\n Umbrafade\n Vellum"], "great_one": True},
        "Ocelot": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Bold\n Fine\n Rosetted\n Pseudo Melanistic\n Melanistic Charcoal\n Melanistic\n Erythristic Red\n Erythristic Isabelline\n Albino\n Piebald\n Leucistic"], "great_one": False},
        "Puma": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino\n Dark Red\n Grey\n Light Brown\n Melanistic"], "great_one": False},
        "South American Tapir": {"max_level": 9, "diamond_min": 144.00, "rare_furs": ["Albino\n Brown\n Brown Grey\n Erythristic\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Spectacled Bear": {"max_level": 9, "diamond_min": 20.45, "rare_furs": ["X markings\n Messy markings\n Glasses markings\n Minimalistic markings\n Abundant markings\n No markings\n Blonde faced\n Piebald\n Leucistic\n Melanistic\n Erythristic Red\n Erythristic Isabelline\n Albino"], "great_one": False},
        "Vicuña": {"max_level": 5, "diamond_min": 214.00, "rare_furs": ["Albino\n Beige\n Dark\n Dilute Silver\n Erythristic Isabelline\n Leucistic\n Melanistic\n Piebald"], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino\n Brown\n Dark-Brown\n Melanistic\n Piebald\n Red-Brown\n Tan"], "great_one": True},
    },
}
