"""Reserve-specific COTW species difficulty, trophy, and fur metadata."""

SPECIES_METADATA = {
    0: {
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Roe Deer": {"max_level": 3, "diamond_min": 81.80, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "European Bison": {"max_level": 5, "diamond_min": 300.00, "rare_furs": ["Albino", "Piebald"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
    },
    1: {
        "Roosevelt Elk": {"max_level": 5, "diamond_min": 380.84, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Grizzly Bear": {"max_level": 9, "diamond_min": 66.94, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Blacktail Deer": {"max_level": 5, "diamond_min": 177.58, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Coyote": {"max_level": 9, "diamond_min": 56.87, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": ["Albino", "Melanistic", "Blonde", "Piebald"], "great_one": False},
    },
    2: {
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Reindeer": {"max_level": 5, "diamond_min": 430.23, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Brown Bear": {"max_level": 9, "diamond_min": 27.70, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "Siberian Musk Deer": {"max_level": 3, "diamond_min": 249.00, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Capercaillie": {"max_level": 3, "diamond_min": 4.64, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Eurasian Lynx": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
    },
    3: {
        "Scrub Hare": {"max_level": 3, "diamond_min": 6.00, "rare_furs": ["Albino"], "great_one": False},
        "Side-Striped Jackal": {"max_level": 9, "diamond_min": 31.00, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Springbok": {"max_level": 5, "diamond_min": 116.00, "rare_furs": ["Albino", "Black-Brown"], "great_one": False},
        "Warthog": {"max_level": 5, "diamond_min": 63.00, "rare_furs": ["Albino", "Red"], "great_one": False},
        "Lesser Kudu": {"max_level": 5, "diamond_min": 35.00, "rare_furs": ["Albino"], "great_one": False},
        "Blue Wildebeest": {"max_level": 5, "diamond_min": 37.70, "rare_furs": ["Albino", "Crowned"], "great_one": False},
        "Gemsbok": {"max_level": 5, "diamond_min": 336.20, "rare_furs": ["Gold"], "great_one": False},
        "Cape Buffalo": {"max_level": 9, "diamond_min": 151.30, "rare_furs": ["Albino"], "great_one": False},
        "Lion": {"max_level": 9, "diamond_min": 48.50, "rare_furs": ["Albino", "Blonde"], "great_one": False},
    },
    4: {
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino", "Melanistic", "Dilute"], "great_one": True},
        "Blackbuck": {"max_level": 5, "diamond_min": 132.26, "rare_furs": ["Leucistic"], "great_one": False},
        "Axis Deer": {"max_level": 5, "diamond_min": 217.29, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Puma": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Water Buffalo": {"max_level": 9, "diamond_min": 167.54, "rare_furs": ["Albino"], "great_one": False},
        "Cinnamon Teal": {"max_level": 3, "diamond_min": 4.60, "rare_furs": ["Piebald"], "great_one": False},
    },
    6: {
        "Grizzly Bear": {"max_level": 9, "diamond_min": 66.94, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Caribou": {"max_level": 5, "diamond_min": 430.23, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Gray Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "Harlequin Duck": {"max_level": 3, "diamond_min": 7.20, "rare_furs": ["Piebald"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Plains Bison": {"max_level": 5, "diamond_min": 183.50, "rare_furs": ["Albino"], "great_one": False},
    },
    8: {
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Roe Deer": {"max_level": 3, "diamond_min": 81.80, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "European Rabbit": {"max_level": 3, "diamond_min": 2.42, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Iberian Mouflon": {"max_level": 5, "diamond_min": 179.56, "rare_furs": ["Albino"], "great_one": False},
        "Ronda Ibex": {"max_level": 5, "diamond_min": 107.98, "rare_furs": ["Albino"], "great_one": False},
        "Beceite Ibex": {"max_level": 5, "diamond_min": 191.63, "rare_furs": ["Albino"], "great_one": False},
        "Gredos Ibex": {"max_level": 5, "diamond_min": 100.17, "rare_furs": ["Albino"], "great_one": False},
        "Southeastern Spanish Ibex": {"max_level": 5, "diamond_min": 89.68, "rare_furs": ["Albino"], "great_one": False},
        "Iberian Wolf": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino", "Fantasma", "Sombra"], "great_one": False},
        "Ring-Necked Pheasant": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
    },
    9: {
        "Rocky Mountain Elk": {"max_level": 5, "diamond_min": 481.41, "rare_furs": ["Albino", "Piebald"], "great_one": False},
        "Bighorn Sheep": {"max_level": 5, "diamond_min": 196.64, "rare_furs": ["Albino"], "great_one": False},
        "Mountain Goat": {"max_level": 5, "diamond_min": 107.67, "rare_furs": ["Albino"], "great_one": False},
        "Pronghorn": {"max_level": 5, "diamond_min": 98.02, "rare_furs": ["Albino", "Dark"], "great_one": False},
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino", "Melanistic", "Dilute"], "great_one": True},
        "White-tailed Jackrabbit": {"max_level": 3, "diamond_min": 6.33, "rare_furs": ["Albino"], "great_one": False},
        "Merriam's Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Albino", "Brown", "Cinnamon"], "great_one": True},
        "Mountain Lion": {"max_level": 9, "diamond_min": 39.00, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
    },
    10: {
        "Chamois": {"max_level": 5, "diamond_min": 58.00, "rare_furs": ["Albino"], "great_one": False},
        "Feral Goat": {"max_level": 5, "diamond_min": 208.71, "rare_furs": ["Albino"], "great_one": False},
        "Sika Deer": {"max_level": 5, "diamond_min": 198.74, "rare_furs": ["Albino", "Black"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Wild Boar": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": ["Albino", "Melanistic", "Blonde", "Piebald"], "great_one": False},
    },
    11: {
        "Mule Deer": {"max_level": 5, "diamond_min": 312.17, "rare_furs": ["Albino", "Melanistic", "Dilute"], "great_one": True},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Bighorn Sheep": {"max_level": 5, "diamond_min": 196.64, "rare_furs": ["Albino"], "great_one": False},
        "Collared Peccary": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino"], "great_one": False},
        "Mexican Bobcat": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino", "Blue"], "great_one": False},
        "Rio Grande Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Cinnamon Teal": {"max_level": 3, "diamond_min": 4.60, "rare_furs": ["Piebald"], "great_one": False},
        "Blackbuck": {"max_level": 5, "diamond_min": 132.26, "rare_furs": ["Leucistic"], "great_one": False},
        "Axis Deer": {"max_level": 5, "diamond_min": 217.29, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
    },
    12: {
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Wild Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Bobwhite Quail": {"max_level": 3, "diamond_min": 238.00, "rare_furs": ["Albino"], "great_one": False},
        "Eastern Cottontail Rabbit": {"max_level": 3, "diamond_min": 1.97, "rare_furs": ["Albino"], "great_one": False},
        "Common Raccoon": {"max_level": 5, "diamond_min": 12.00, "rare_furs": ["Albino", "Blond"], "great_one": False},
        "Gray Fox": {"max_level": 9, "diamond_min": 6.43, "rare_furs": ["Albino"], "great_one": False},
        "Wild Hog": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "American Alligator": {"max_level": 9, "diamond_min": 480.00, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Albino", "Brown", "Cinnamon"], "great_one": True},
        "Bobcat": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino", "Blue"], "great_one": False},
    },
    13: {
        "Eurasian Wigeon": {"max_level": 3, "diamond_min": 900.00, "rare_furs": ["Albino"], "great_one": False},
        "Eurasian Teal": {"max_level": 3, "diamond_min": 300.00, "rare_furs": ["Albino"], "great_one": False},
        "Black Grouse": {"max_level": 3, "diamond_min": 83.00, "rare_furs": ["Albino"], "great_one": False},
        "Goldeneye": {"max_level": 3, "diamond_min": 1100.00, "rare_furs": ["Albino"], "great_one": False},
        "Hazel Grouse": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino"], "great_one": False},
        "Mallard": {"max_level": 3, "diamond_min": 19.61, "rare_furs": ["Albino", "Melanistic", "Blonde", "Piebald"], "great_one": False},
        "Western Capercaillie": {"max_level": 3, "diamond_min": 4.64, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Tufted Duck": {"max_level": 3, "diamond_min": 950.00, "rare_furs": ["Albino"], "great_one": False},
        "Rock Ptarmigan": {"max_level": 3, "diamond_min": 245.00, "rare_furs": ["Albino"], "great_one": False},
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Willow Ptarmigan": {"max_level": 3, "diamond_min": 245.00, "rare_furs": ["Albino"], "great_one": False},
        "Tundra Bean Goose": {"max_level": 5, "diamond_min": 175.00, "rare_furs": ["Albino"], "great_one": False},
        "Mountain Hare": {"max_level": 3, "diamond_min": 6.00, "rare_furs": ["Albino"], "great_one": False},
        "Greylag Goose": {"max_level": 5, "diamond_min": 240.00, "rare_furs": ["Albino"], "great_one": False},
        "Raccoon Dog": {"max_level": 9, "diamond_min": 12.00, "rare_furs": ["Albino"], "great_one": False},
        "Eurasian Lynx": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Eurasian Brown Bear": {"max_level": 9, "diamond_min": 27.70, "rare_furs": ["Albino", "Melanistic"], "great_one": False},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
    },
    14: {
        "Whitetail Deer": {"max_level": 3, "diamond_min": 255.09, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Moose": {"max_level": 5, "diamond_min": 274.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Black Bear": {"max_level": 9, "diamond_min": 22.80, "rare_furs": ["Albino", "Brown", "Cinnamon"], "great_one": True},
        "Bobcat": {"max_level": 9, "diamond_min": 27.68, "rare_furs": ["Albino", "Blue"], "great_one": False},
        "Coyote": {"max_level": 9, "diamond_min": 56.87, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Eastern Wild Turkey": {"max_level": 3, "diamond_min": 4.62, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
        "Green-winged Teal": {"max_level": 3, "diamond_min": 480.00, "rare_furs": ["Piebald"], "great_one": False},
        "Canada Goose": {"max_level": 5, "diamond_min": 8.59, "rare_furs": ["Albino", "Leucistic"], "great_one": False},
    },
    16: {
        "Magpie Goose": {"max_level": 5, "diamond_min": 3.85, "rare_furs": ["Albino"], "great_one": False},
        "Stubble Quail": {"max_level": 3, "diamond_min": 300.00, "rare_furs": ["Albino"], "great_one": False},
        "Red Fox": {"max_level": 9, "diamond_min": 14.05, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Hog Deer": {"max_level": 5, "diamond_min": 112.00, "rare_furs": ["Albino"], "great_one": False},
        "Axis Deer": {"max_level": 5, "diamond_min": 217.29, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": False},
        "Feral Goat": {"max_level": 5, "diamond_min": 208.71, "rare_furs": ["Albino"], "great_one": False},
        "Eastern Grey Kangaroo": {"max_level": 5, "diamond_min": 450.00, "rare_furs": ["Albino"], "great_one": False},
        "Fallow Deer": {"max_level": 5, "diamond_min": 249.99, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Feral Pig": {"max_level": 5, "diamond_min": 144.25, "rare_furs": ["Albino", "Melanistic"], "great_one": True},
        "Red Deer": {"max_level": 9, "diamond_min": 251.07, "rare_furs": ["Albino", "Melanistic", "Piebald"], "great_one": True},
        "Sambar": {"max_level": 5, "diamond_min": 215.00, "rare_furs": ["Albino"], "great_one": False},
        "Sambar Deer": {"max_level": 5, "diamond_min": 215.00, "rare_furs": ["Albino"], "great_one": False},
        "Javan Rusa": {"max_level": 5, "diamond_min": 175.00, "rare_furs": ["Albino"], "great_one": False},
        "Saltwater Crocodile": {"max_level": 9, "diamond_min": 480.00, "rare_furs": ["Albino", "Piebald"], "great_one": False},
        "Banteng": {"max_level": 5, "diamond_min": 135.00, "rare_furs": ["Albino"], "great_one": False},
    },
}
